### ISSUE TITLE
React Nantes

### ISSUE THREAD

**Issue by LudiDrouet** [nantes-tech-communities/list-communities#61]
# React Nantes
| | |
| --- | --- |
| :email: Qui contacter ? |[Anaïs](https://www.meetup.com/React-Nantes/members/211519287/profile/?returnPage=1) /  [Godefroy](https://www.meetup.com/React-Nantes/members/14410215/profile/?returnPage=1) / [Guillaume](https://www.meetup.com/React-Nantes/members/218224376/profile/?returnPage=1) / [Jean-Baptiste ](https://www.meetup.com/React-Nantes/members/246660205/profile/?returnPage=1) / [Ludivine](https://www.meetup.com/React-Nantes/members/357066930/profile/?returnPage=1) / [Matthieu](https://www.meetup.com/React-Nantes/members/147517082/profile/?returnPage=1)  |
| 🌍 Le site web| https://www.meetup.com/React-Nantes |
| ✨ Slack| https://join.slack.com/t/reactnantes/shared_invite/zt-4oxtcvfn-yvqall5Uqn47rtW5OvTk5g |

**Comment by jeanphibaconnais** [comment]
Hello @LudiDrouet , as tu besoin d'aide pour pouvoir soumettre ces infos dans le repo ? (il faut passer par un fork du projet, PR, etc ? )
La semaine prochaine on peut se prévoir cela si tu veux / peux

**Comment by LudiDrouet** [comment]
Hello @jeanphibaconnais 
Oui, je veux bien que tu m'aides :-) 
Je suis dispo lundi ou mercredi la semaine prochaine

**Comment by jeanphibaconnais** [comment]
resolve https://github.com/nantes-tech-communities/list-communities/pull/62
